"""Init tables

Revision ID: 364a09a4c194
Revises: 
Create Date: 2025-12-08 10:32:44.344235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '364a09a4c194'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('bundle_id', sa.String(), nullable=True),
    sa.Column('platform', sa.String(), nullable=True),
    sa.Column('appmetrica_app_id', sa.String(), nullable=False),
    sa.Column('appmetrica_api_key', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_games_bundle_id'), 'games', ['bundle_id'], unique=True)
    op.create_index(op.f('ix_games_id'), 'games', ['id'], unique=False)
    op.create_table('raw_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('event_name', sa.String(), nullable=True),
    sa.Column('event_timestamp', sa.DateTime(), nullable=True),
    sa.Column('event_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_events_event_name'), 'raw_events', ['event_name'], unique=False)
    op.create_index(op.f('ix_raw_events_event_timestamp'), 'raw_events', ['event_timestamp'], unique=False)
    op.create_index(op.f('ix_raw_events_id'), 'raw_events', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_raw_events_id'), table_name='raw_events')
    op.drop_index(op.f('ix_raw_events_event_timestamp'), table_name='raw_events')
    op.drop_index(op.f('ix_raw_events_event_name'), table_name='raw_events')
    op.drop_table('raw_events')
    op.drop_index(op.f('ix_games_id'), table_name='games')
    op.drop_index(op.f('ix_games_bundle_id'), table_name='games')
    op.drop_table('games')
    # ### end Alembic commands ###
