"""Add processed_reports table

Revision ID: 698575932500
Revises: bf5d3aeae4c3
Create Date: 2025-12-08 11:44:10.122072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '698575932500'
down_revision: Union[str, Sequence[str], None] = 'bf5d3aeae4c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processed_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('dau', sa.Integer(), nullable=True),
    sa.Column('revenue', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processed_reports_date'), 'processed_reports', ['date'], unique=False)
    op.create_index(op.f('ix_processed_reports_id'), 'processed_reports', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_processed_reports_id'), table_name='processed_reports')
    op.drop_index(op.f('ix_processed_reports_date'), table_name='processed_reports')
    op.drop_table('processed_reports')
    # ### end Alembic commands ###
