"""Add booster table

Revision ID: bf5d3aeae4c3
Revises: 364a09a4c194
Create Date: 2025-12-08 11:04:12.965306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf5d3aeae4c3'
down_revision: Union[str, Sequence[str], None] = '364a09a4c194'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('boosters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('booster_id_in_log', sa.String(), nullable=True),
    sa.Column('friendly_name', sa.String(), nullable=True),
    sa.Column('price_usd', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_boosters_booster_id_in_log'), 'boosters', ['booster_id_in_log'], unique=False)
    op.create_index(op.f('ix_boosters_id'), 'boosters', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_boosters_id'), table_name='boosters')
    op.drop_index(op.f('ix_boosters_booster_id_in_log'), table_name='boosters')
    op.drop_table('boosters')
    # ### end Alembic commands ###
