"""Add processed_reports table

Revision ID: c167b6630cc3
Revises: 698575932500
Create Date: 2025-12-08 13:01:25.620277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c167b6630cc3'
down_revision: Union[str, Sequence[str], None] = '698575932500'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('processed_reports', sa.Column('new_users', sa.Integer(), nullable=True))
    op.alter_column('processed_reports', 'date',
               existing_type=sa.DATE(),
               nullable=False)
    op.create_unique_constraint('uix_game_date', 'processed_reports', ['game_id', 'date'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_game_date', 'processed_reports', type_='unique')
    op.alter_column('processed_reports', 'date',
               existing_type=sa.DATE(),
               nullable=True)
    op.drop_column('processed_reports', 'new_users')
    # ### end Alembic commands ###
